PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS LikeComment (
	PostId VARCHAR(36) NOT NULL,
	UserId VARCHAR(36) NOT NULL,

	CONSTRAINT fk_postid FOREIGN KEY (PostId) REFERENCES "Post"("Id") ON DELETE CASCADE,
	CONSTRAINT fk_userid FOREIGN KEY (UserId) REFERENCES "UserInfo"("Id") ON DELETE CASCADE
);