DROP TABLE IF EXISTS Auth;
DROP TABLE IF EXISTS UserInfo;
DROP TABLE IF EXISTS Post;
DROP TABLE IF EXISTS Comment;
DROP TABLE IF EXISTS Follower;
DROP TABLE IF EXISTS Groups;

DROP VIEW IF EXISTS PostDetail;