PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS FollowingRequest (
	UserId VARCHAR(36) NOT NULL,
	FollowerId VARCHAR(36) NOT NULL,

	CONSTRAINT fk_userid FOREIGN KEY (UserId) REFERENCES "UserInfo"("Id") ON DELETE CASCADE,
	CONSTRAINT fk_followerid FOREIGN KEY (FollowerId) REFERENCES "UserInfo"("Id") ON DELETE CASCADE
)