CREATE TABLE IF NOT EXISTS UserInfo (
	Id VARCHAR(36) NOT NULL UNIQUE,
	Email VARCHAR(100) NOT NULL UNIQUE,
	FirstName VARCHAR(50) NOT NULL, 
	LastName VARCHAR(50) NOT NULL,
	BirthDate VARCHAR(20) NOT NULL,
	ProfilePicture VARCHAR(400000),
	Username VARCHAR(50),
	AboutMe VARCHAR(280),

	CONSTRAINT fk_id FOREIGN KEY (Id) REFERENCES "Auth"("Id")
);