DROP TABLE IF EXISTS Auth;
DROP TABLE IF EXISTS UserInfo;
DROP TABLE IF EXISTS Post;
DROP TABLE IF EXISTS LikePost;
DROP TABLE IF EXISTS DislikePost;
DROP TABLE IF EXISTS Comment;
DROP TABLE IF EXISTS LikeComment;
DROP TABLE IF EXISTS DislikeComment;
DROP TABLE IF EXISTS Follower;
DROP TABLE IF EXISTS Groups;

DROP VIEW IF EXISTS PostDetail;