CREATE TABLE IF NOT EXISTS Auth (
	Id VARCHAR(36) NOT NULL PRIMARY KEY,
	Email VARCHAR(100) NOT NULL,
	Password VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS UserInfo (
	Id VARCHAR(36) NOT NULL REFERENCES "Auth"("Id"),
	Email VARCHAR(100) NOT NULL REFERENCES "Auth"("Email"),
	FirstName VARCHAR(50) NOT NULL, 
	LastName VARCHAR(50) NOT NULL,
	Birth VARCHAR(20) NOT NULL,
	Avatar VARCHAR(100),
	Username VARCHAR(50),
	AboutMe VARCHAR(280)  
);