CREATE TABLE IF NOT EXISTS Auth (
	Id VARCHAR(36) NOT NULL UNIQUE PRIMARY KEY,
	Email VARCHAR(100) NOT NULL UNIQUE,
	Password VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS UserInfo (
	Id VARCHAR(36) NOT NULL UNIQUE REFERENCES "Auth"("Id"),
	Email VARCHAR(100) NOT NULL UNIQUE REFERENCES "Auth"("Email"),
	FirstName VARCHAR(50) NOT NULL, 
	LastName VARCHAR(50) NOT NULL,
	BirthDate VARCHAR(20) NOT NULL,
	ProfilePicture VARCHAR(100),
	Username VARCHAR(50),
	AboutMe VARCHAR(280)  
);